[colors]
[colors.primary]
background = "#0d0b09"
foreground = "#ffffff"

[colors.normal]
black   = "#0d0b09"
red     = "#c8b6b4"
green   = "#87a2b0"
yellow  = "#d5905e"
blue    = "#97afbf"
magenta = "#cda498"
cyan    = "#c4c5c6"
white   = "#e3dbdb"

[colors.bright]
black   = "#897e72"
red     = "#efe9e9"
green   = "#bdcdd6"
yellow  = "#ebc2a4"
blue    = "#cfdbe3"
magenta = "#ecdad5"
cyan    = "#f3f3f3"
white   = "#ffffff"

[colors.cursor]
text   = "#0d0b09"
cursor = "#ffffff"
